<?php

return [
    'ranker' => [
        // true: use weighted ranking; false: keep insertion order.
        'enabled' => true,
        'weights' => [
            'tag_query_match' => 120,
            'boost_tag_match' => 36,
            'boost_tag_secondary_match' => 18,
            'city_match' => 80,
            'tab_semantic_tag' => 15,
            'scene_hint' => 6,
            'likes_divisor' => 10,
        ],
    ],

    'banner' => [
        'title' => '本周关系进展',
        'subtitle' => '查看匹配亮点，安排一场轻松的同城见面',
        'cta' => '查看本周匹配',
    ],

    'shortcuts' => [
        ['key' => 'questionnaire', 'title' => '继续问卷', 'action' => 'route', 'target' => '/questionnaire'],
        ['key' => 'status', 'title' => '发布状态', 'action' => 'route', 'target' => '/status/square'],
        ['key' => 'match', 'title' => '本周匹配', 'action' => 'route', 'target' => '/match'],
        ['key' => 'astro', 'title' => '星盘画像', 'action' => 'route', 'target' => '/profile/astro'],
        ['key' => 'discover', 'title' => '同城活动', 'action' => 'route', 'target' => '/discover'],
    ],

    'items' => [
        [
            'id' => 'home-001',
            'scene' => 'home',
            'tabs' => ['recommend', 'topic'],
            'city' => 'all',
            'title' => '第一次聊天别急着自我介绍，先交换一个小偏好',
            'summary' => '用“最近在循环听的一首歌”破冰，能显著提升对话持续率。',
            'author' => '慢约会研究组',
            'likes' => 128,
            'tags' => ['沟通技巧', '关系研究'],
            'media' => [],
            'body' => '对话开场最怕像面试。先交换轻偏好，再进入价值观话题，会更自然。',
        ],
        [
            'id' => 'home-002',
            'scene' => 'home',
            'tabs' => ['recommend', 'event'],
            'city' => '南阳',
            'title' => '同城周末活动：南阳白河夜跑组队',
            'summary' => '3公里轻社交路线，适合首次线下见面。',
            'author' => '同城活动官',
            'likes' => 96,
            'tags' => ['同城', '活动'],
            'media' => [],
            'body' => '活动集合点与时间已更新，建议提前10分钟到场。',
        ],
        [
            'id' => 'home-003',
            'scene' => 'home',
            'tabs' => ['recommend', 'topic'],
            'city' => 'all',
            'title' => '匹配后 24 小时内回复率最高的话题类型',
            'summary' => '“最近一次小确幸”比“你做什么工作”更容易延续对话。',
            'author' => '慢约会研究组',
            'likes' => 154,
            'tags' => ['匹配提升', '沟通技巧'],
            'media' => [],
            'body' => '先分享一件具体小事，能快速建立情绪同步与信任感。',
        ],
        [
            'id' => 'home-004',
            'scene' => 'home',
            'tabs' => ['nearby', 'event'],
            'city' => '深圳',
            'title' => '深圳城市漫步：书店与咖啡路线',
            'summary' => '低压力见面路线，适合首次同城互动。',
            'author' => '同城活动官',
            'likes' => 87,
            'tags' => ['同城', '活动'],
            'media' => [],
            'body' => '路线包含两段步行与一个固定休息点，便于自然聊天。',
        ],
        [
            'id' => 'home-005',
            'scene' => 'home',
            'tabs' => ['inspire', 'topic'],
            'city' => 'all',
            'title' => '关系灵感：如何把“晚安”说得不套路',
            'summary' => '用“今天你最开心的一刻是什么”替代模板话术。',
            'author' => '慢约会编辑部',
            'likes' => 133,
            'tags' => ['关系研究', '灵感'],
            'media' => [],
            'body' => '晚安不是流程，而是一天情绪的轻收尾。',
        ],
        [
            'id' => 'home-006',
            'scene' => 'home',
            'tabs' => ['recommend', 'nearby'],
            'city' => '上海',
            'title' => '上海午休散步局：20分钟轻聊天',
            'summary' => '中午时间短见面，降低首次交流压力。',
            'author' => '同城活动官',
            'likes' => 74,
            'tags' => ['同城', '轻活动'],
            'media' => [],
            'body' => '短时见面更容易保持轻松感，适合第一次线下破冰。',
        ],
        [
            'id' => 'home-007',
            'scene' => 'home',
            'tabs' => ['topic', 'inspire'],
            'city' => 'all',
            'title' => '聊天节奏小技巧：先问“最近忙什么”再问“想成为什么”',
            'summary' => '从当下状态切到长期目标，过渡更自然。',
            'author' => '慢约会研究组',
            'likes' => 142,
            'tags' => ['沟通技巧', '匹配提升'],
            'media' => [],
            'body' => '先让对方进入熟悉话题，再逐步展开价值观，会减少防御感。',
        ],
        [
            'id' => 'home-008',
            'scene' => 'home',
            'tabs' => ['event', 'nearby'],
            'city' => '广州',
            'title' => '广州夜市小队：边走边聊的约会场景',
            'summary' => '开放环境下更容易自然开启话题。',
            'author' => '活动策划',
            'likes' => 65,
            'tags' => ['活动', '同城'],
            'media' => [],
            'body' => '动态场景能降低“对坐面试感”，适合首次见面。',
        ],
        [
            'id' => 'home-009',
            'scene' => 'home',
            'tabs' => ['recommend'],
            'city' => 'all',
            'title' => '研究小结：匹配后 72 小时内建立固定问候更稳',
            'summary' => '固定节奏比“高频轰炸”更能提升关系稳定性。',
            'author' => '慢约会研究组',
            'likes' => 168,
            'tags' => ['关系研究', '匹配提升'],
            'media' => [],
            'body' => '建议约定一个低压力的固定联系时段，形成正向预期。',
        ],
        [
            'id' => 'home-010',
            'scene' => 'home',
            'tabs' => ['inspire'],
            'city' => 'all',
            'title' => '关系灵感：如何优雅结束一次不合适的聊天',
            'summary' => '诚实表达边界，比“突然消失”更成熟。',
            'author' => '慢约会编辑部',
            'likes' => 111,
            'tags' => ['灵感', '关系研究'],
            'media' => [],
            'body' => '边界清晰是对彼此的尊重，也有助于平台交流氛围。',
        ],
        [
            'id' => 'home-011',
            'scene' => 'home',
            'tabs' => ['nearby', 'event'],
            'city' => '北京',
            'title' => '北京一句话推荐：下班后公园散步比咖啡厅更容易放松',
            'summary' => '步行场景降低拘谨感，适合第一次见面。',
            'author' => '同城活动官',
            'likes' => 72,
            'tags' => ['同城', '活动'],
            'media' => [],
            'body' => '先走后坐，聊天更自然。',
        ],
        [
            'id' => 'home-012',
            'scene' => 'home',
            'tabs' => ['nearby', 'event'],
            'city' => '上海',
            'title' => '上海一句话推荐：午休 20 分钟见面，效率高也不尴尬',
            'summary' => '短时见面更适合先建立安全感。',
            'author' => '同城活动官',
            'likes' => 68,
            'tags' => ['同城', '轻活动'],
            'media' => [],
            'body' => '短见面，长预期。',
        ],
        [
            'id' => 'home-013',
            'scene' => 'home',
            'tabs' => ['nearby', 'event'],
            'city' => '广州',
            'title' => '广州一句话推荐：夜市并排走，沉默也不会尴尬',
            'summary' => '动态场景可减少对视压力。',
            'author' => '活动策划',
            'likes' => 64,
            'tags' => ['同城', '活动'],
            'media' => [],
            'body' => '同向而行，聊天更顺。',
        ],
        [
            'id' => 'home-014',
            'scene' => 'home',
            'tabs' => ['nearby', 'event'],
            'city' => '深圳',
            'title' => '深圳一句话推荐：海边骑行 30 分钟是高通过率破冰场景',
            'summary' => '轻运动有助于缓解首次见面的紧张感。',
            'author' => '活动策划',
            'likes' => 70,
            'tags' => ['同城', '活动'],
            'media' => [],
            'body' => '轻运动，低压力。',
        ],
        [
            'id' => 'home-015',
            'scene' => 'home',
            'tabs' => ['nearby', 'event'],
            'city' => '南阳',
            'title' => '南阳一句话推荐：白河边慢跑后喝水，比正襟危坐更自然',
            'summary' => '轻活动能快速建立熟悉感。',
            'author' => '同城活动官',
            'likes' => 59,
            'tags' => ['同城', '活动'],
            'media' => [],
            'body' => '先动起来，再聊深入。',
        ],
        [
            'id' => 'home-016',
            'scene' => 'home',
            'tabs' => ['topic'],
            'city' => 'all',
            'title' => '一句话沟通技巧：先讲“我最近”再问“你怎么看”',
            'summary' => '先自我暴露一点点，回应率会更高。',
            'author' => '慢约会研究组',
            'likes' => 118,
            'tags' => ['沟通技巧', '匹配提升'],
            'media' => [],
            'body' => '先给对方安全入口。',
        ],
        [
            'id' => 'home-017',
            'scene' => 'home',
            'tabs' => ['topic'],
            'city' => 'all',
            'title' => '一句话关系建议：高频不如稳定，稳定不如可预期',
            'summary' => '固定节奏比临时热情更能建立信任。',
            'author' => '慢约会研究组',
            'likes' => 126,
            'tags' => ['关系研究', '匹配提升'],
            'media' => [],
            'body' => '持续一致比偶发惊喜更重要。',
        ],
        [
            'id' => 'home-018',
            'scene' => 'home',
            'tabs' => ['inspire'],
            'city' => 'all',
            'title' => '一句话灵感：把“在吗”换成“我刚看到一个有趣细节”',
            'summary' => '具体信息比空问候更容易接话。',
            'author' => '慢约会编辑部',
            'likes' => 91,
            'tags' => ['灵感', '沟通技巧'],
            'media' => [],
            'body' => '具体，才能被回应。',
        ],
        [
            'id' => 'home-019',
            'scene' => 'home',
            'tabs' => ['recommend'],
            'city' => '北京',
            'title' => '北京同城提醒：周三晚活动报名率通常高于周一',
            'summary' => '工作节奏影响见面意愿，选时很关键。',
            'author' => '同城活动官',
            'likes' => 53,
            'tags' => ['同城', '匹配提升'],
            'media' => [],
            'body' => '选对时间，事半功倍。',
        ],
        [
            'id' => 'home-020',
            'scene' => 'home',
            'tabs' => ['recommend'],
            'city' => '上海',
            'title' => '上海同城提醒：地铁 30 分钟圈是最优首见半径',
            'summary' => '减少通勤成本，见面成功率更高。',
            'author' => '同城活动官',
            'likes' => 57,
            'tags' => ['同城', '关系研究'],
            'media' => [],
            'body' => '距离短，决策快。',
        ],
        [
            'id' => 'discover-101',
            'scene' => 'discover',
            'tabs' => ['hot', 'topic'],
            'city' => 'all',
            'title' => '热点话题：异地恋最难的不是距离',
            'summary' => '参与讨论并查看不同城市用户的真实经验。',
            'author' => '社区运营',
            'likes' => 201,
            'tags' => ['话题', '热点'],
            'media' => [],
            'body' => '稳定沟通频率与预期管理，往往比距离本身更关键。',
        ],
        [
            'id' => 'discover-102',
            'scene' => 'discover',
            'tabs' => ['local', 'event'],
            'city' => '北京',
            'title' => '北京同城活动：博物馆共读日',
            'summary' => '报名后可进入活动群，提前认识同场用户。',
            'author' => '同城活动官',
            'likes' => 119,
            'tags' => ['同城', '活动'],
            'media' => [],
            'body' => '活动分为自由观展与共读交流两段，节奏轻松。',
        ],
        [
            'id' => 'discover-103',
            'scene' => 'discover',
            'tabs' => ['event'],
            'city' => '广州',
            'title' => '广州周末桌游局：破冰专场',
            'summary' => '适合初次见面的低门槛活动，含引导主持。',
            'author' => '活动策划',
            'likes' => 108,
            'tags' => ['活动', '破冰'],
            'media' => [],
            'body' => '活动提供新手引导，减少第一次见面的紧张感。',
        ],
        [
            'id' => 'discover-104',
            'scene' => 'discover',
            'tabs' => ['topic'],
            'city' => 'all',
            'title' => '讨论区：你更看重“稳定”还是“激情”？',
            'summary' => '投票后可查看不同年龄段用户的分布结果。',
            'author' => '社区运营',
            'likes' => 173,
            'tags' => ['话题', '关系研究'],
            'media' => [],
            'body' => '关系中的稳定与激情并非对立，关键在节奏与边界。',
        ],
        [
            'id' => 'discover-105',
            'scene' => 'discover',
            'tabs' => ['live'],
            'city' => 'all',
            'title' => '语音房：第一次见面聊什么不尴尬',
            'summary' => '今晚 20:30 开房，支持匿名上麦。',
            'author' => '语音主持',
            'likes' => 141,
            'tags' => ['语音房', '沟通技巧'],
            'media' => [],
            'body' => '语音场景下建议先聊轻主题，再过渡到个人价值观。',
        ],
        [
            'id' => 'discover-106',
            'scene' => 'discover',
            'tabs' => ['hot'],
            'city' => 'all',
            'title' => '热门征集：你最想参加哪类第一次约会活动？',
            'summary' => '从散步、展览、咖啡到桌游，看看同城选择趋势。',
            'author' => '社区运营',
            'likes' => 132,
            'tags' => ['热点', '投票'],
            'media' => [],
            'body' => '投票结果将用于下周同城活动排期。',
        ],
        [
            'id' => 'discover-107',
            'scene' => 'discover',
            'tabs' => ['local', 'event'],
            'city' => '深圳',
            'title' => '深圳晚风骑行：慢节奏双人路线',
            'summary' => '路线平缓，沿途有两个休息打卡点。',
            'author' => '同城活动官',
            'likes' => 97,
            'tags' => ['同城', '活动'],
            'media' => [],
            'body' => '适合偏安静型用户，重在共同体验而非强社交。',
        ],
        [
            'id' => 'discover-108',
            'scene' => 'discover',
            'tabs' => ['topic'],
            'city' => 'all',
            'title' => '话题接力：你如何判断“值得继续聊”',
            'summary' => '分享一个你的判断信号，帮助更多人少走弯路。',
            'author' => '社区运营',
            'likes' => 146,
            'tags' => ['话题', '沟通技巧'],
            'media' => [],
            'body' => '当互动有来有回且边界被尊重，通常是积极信号。',
        ],
        [
            'id' => 'discover-109',
            'scene' => 'discover',
            'tabs' => ['event'],
            'city' => '北京',
            'title' => '北京书影音交换夜：偏好即名片',
            'summary' => '带一本书或一部电影推荐，快速进入深聊。',
            'author' => '活动策划',
            'likes' => 88,
            'tags' => ['活动', '破冰'],
            'media' => [],
            'body' => '偏好交换是低门槛的自我表达方式，常用于破冰。',
        ],
        [
            'id' => 'discover-110',
            'scene' => 'discover',
            'tabs' => ['live'],
            'city' => 'all',
            'title' => '语音房：如何判断对方是否愿意认真关系',
            'summary' => '主持人带你拆解“语言信号”和“行为信号”。',
            'author' => '语音主持',
            'likes' => 159,
            'tags' => ['语音房', '关系研究'],
            'media' => [],
            'body' => '单次表达不代表长期稳定，需看持续一致的行为。',
        ],
        [
            'id' => 'discover-111',
            'scene' => 'discover',
            'tabs' => ['local', 'event'],
            'city' => '南阳',
            'title' => '南阳同城：周末人民公园轻社交快闪',
            'summary' => '15分钟互相认识，降低首次交流压力。',
            'author' => '同城活动官',
            'likes' => 46,
            'tags' => ['同城', '活动'],
            'media' => [],
            'body' => '短时破冰，效率更高。',
        ],
        [
            'id' => 'discover-112',
            'scene' => 'discover',
            'tabs' => ['local', 'event'],
            'city' => '上海',
            'title' => '上海同城：下班后书店共读 40 分钟',
            'summary' => '先静后聊，适合慢热型用户。',
            'author' => '活动策划',
            'likes' => 58,
            'tags' => ['同城', '活动'],
            'media' => [],
            'body' => '有共同场景更好开口。',
        ],
        [
            'id' => 'discover-113',
            'scene' => 'discover',
            'tabs' => ['local', 'event'],
            'city' => '广州',
            'title' => '广州同城：骑楼夜拍散步局',
            'summary' => '边走边拍，话题自然产生。',
            'author' => '活动策划',
            'likes' => 52,
            'tags' => ['同城', '活动'],
            'media' => [],
            'body' => '场景就是话题发生器。',
        ],
        [
            'id' => 'discover-114',
            'scene' => 'discover',
            'tabs' => ['local', 'event'],
            'city' => '深圳',
            'title' => '深圳同城：地铁沿线咖啡交换会',
            'summary' => '每人推荐一家店，快速了解生活方式。',
            'author' => '同城活动官',
            'likes' => 55,
            'tags' => ['同城', '活动'],
            'media' => [],
            'body' => '偏好交换比问答更有效。',
        ],
        [
            'id' => 'discover-115',
            'scene' => 'discover',
            'tabs' => ['local', 'event'],
            'city' => '北京',
            'title' => '北京同城：美术馆 30 分钟导览交流',
            'summary' => '共同观看能减少冷场概率。',
            'author' => '同城活动官',
            'likes' => 63,
            'tags' => ['同城', '活动'],
            'media' => [],
            'body' => '先共同体验，再表达观点。',
        ],
        [
            'id' => 'discover-116',
            'scene' => 'discover',
            'tabs' => ['topic'],
            'city' => 'all',
            'title' => '一句话话题：你最看重“回应速度”还是“回应质量”？',
            'summary' => '投票后可查看同城差异。',
            'author' => '社区运营',
            'likes' => 74,
            'tags' => ['话题', '热点'],
            'media' => [],
            'body' => '频率和深度都重要，关键是匹配。',
        ],
        [
            'id' => 'discover-117',
            'scene' => 'discover',
            'tabs' => ['topic'],
            'city' => 'all',
            'title' => '一句话话题：第一次见面你更怕冷场还是迟到？',
            'summary' => '评论区有高赞应对模板。',
            'author' => '社区运营',
            'likes' => 69,
            'tags' => ['话题', '沟通技巧'],
            'media' => [],
            'body' => '提前约定节奏能化解大半焦虑。',
        ],
        [
            'id' => 'discover-118',
            'scene' => 'discover',
            'tabs' => ['hot'],
            'city' => 'all',
            'title' => '热门：同城活动后 24 小时内复盘最能提升二次见面率',
            'summary' => '一句复盘比一串表情更有效。',
            'author' => '慢约会研究组',
            'likes' => 88,
            'tags' => ['热点', '匹配提升'],
            'media' => [],
            'body' => '复盘是关系推进的转折点。',
        ],
        [
            'id' => 'discover-119',
            'scene' => 'discover',
            'tabs' => ['live'],
            'city' => 'all',
            'title' => '语音房：今晚主题“第一次约会怎么结束最体面”',
            'summary' => '支持匿名上麦，主持人给话术模板。',
            'author' => '语音主持',
            'likes' => 77,
            'tags' => ['语音房', '沟通技巧'],
            'media' => [],
            'body' => '收尾体面，关系才有下一次。',
        ],
        [
            'id' => 'discover-120',
            'scene' => 'discover',
            'tabs' => ['event'],
            'city' => '南阳',
            'title' => '南阳活动：周末植物园并排走聊',
            'summary' => '低噪音场景，适合慢速认识。',
            'author' => '同城活动官',
            'likes' => 43,
            'tags' => ['同城', '活动'],
            'media' => [],
            'body' => '并排走路更容易形成节奏同步。',
        ],
    ],
];
