const Map<String, dynamic> astroChartComparisonSampleProfile = {
  'chart_data': {
    'subject': {
      'name': 'EliteSync',
      'city': '北京市朝阳区',
      'iso_formatted_local_datetime': '1996-08-18T10:30:00+08:00',
      'sun': {'name': 'Sun', 'abs_pos': 145.43},
      'moon': {'name': 'Moon', 'abs_pos': 187.44},
      'mercury': {'name': 'Mercury', 'abs_pos': 158.22},
      'venus': {'name': 'Venus', 'abs_pos': 139.18},
      'mars': {'name': 'Mars', 'abs_pos': 201.42},
      'jupiter': {'name': 'Jupiter', 'abs_pos': 236.20},
      'saturn': {'name': 'Saturn', 'abs_pos': 271.08},
      'uranus': {'name': 'Uranus', 'abs_pos': 312.25},
      'neptune': {'name': 'Neptune', 'abs_pos': 341.12},
      'pluto': {'name': 'Pluto', 'abs_pos': 231.10},
      'chiron': {'name': 'Chiron', 'abs_pos': 296.62},
      'ascendant': {'name': 'Ascendant', 'abs_pos': 204.45},
      'descendant': {'name': 'Descendant', 'abs_pos': 24.45},
      'medium_coeli': {'name': 'Medium_Coeli', 'abs_pos': 114.45},
      'imum_coeli': {'name': 'Imum_Coeli', 'abs_pos': 294.45},
      'mean_north_lunar_node': {
        'name': 'Mean_North_Lunar_Node',
        'abs_pos': 48.50,
      },
      'true_north_lunar_node': {
        'name': 'True_North_Lunar_Node',
        'abs_pos': 49.10,
      },
      'mean_south_lunar_node': {
        'name': 'Mean_South_Lunar_Node',
        'abs_pos': 228.50,
      },
      'true_south_lunar_node': {
        'name': 'True_South_Lunar_Node',
        'abs_pos': 229.10,
      },
      'earth': {'name': 'Earth', 'abs_pos': 11.10},
      'first_house': {'name': 'First_House', 'abs_pos': 204.45},
      'second_house': {'name': 'Second_House', 'abs_pos': 234.45},
      'third_house': {'name': 'Third_House', 'abs_pos': 264.45},
      'fourth_house': {'name': 'Fourth_House', 'abs_pos': 294.45},
      'fifth_house': {'name': 'Fifth_House', 'abs_pos': 324.45},
      'sixth_house': {'name': 'Sixth_House', 'abs_pos': 354.45},
      'seventh_house': {'name': 'Seventh_House', 'abs_pos': 24.45},
      'eighth_house': {'name': 'Eighth_House', 'abs_pos': 54.45},
      'ninth_house': {'name': 'Ninth_House', 'abs_pos': 84.45},
      'tenth_house': {'name': 'Tenth_House', 'abs_pos': 114.45},
      'eleventh_house': {'name': 'Eleventh_House', 'abs_pos': 144.45},
      'twelfth_house': {'name': 'Twelfth_House', 'abs_pos': 174.45},
    },
    'aspects': [
      {'p1_name': 'Sun', 'p2_name': 'Moon', 'aspect': 'sextile', 'orbit': 1.0},
      {'p1_name': 'Sun', 'p2_name': 'Mercury', 'aspect': 'trine', 'orbit': 2.2},
      {'p1_name': 'Moon', 'p2_name': 'Venus', 'aspect': 'square', 'orbit': 3.8},
      {
        'p1_name': 'Jupiter',
        'p2_name': 'Saturn',
        'aspect': 'opposition',
        'orbit': 5.2,
      },
      {
        'p1_name': 'Mercury',
        'p2_name': 'Mars',
        'aspect': 'semisquare',
        'orbit': 4.1,
      },
      {
        'p1_name': 'Pluto',
        'p2_name': 'Chiron',
        'aspect': 'quincunx',
        'orbit': 2.8,
      },
      {
        'p1_name': 'Ascendant',
        'p2_name': 'Medium_Coeli',
        'aspect': 'square',
        'orbit': 1.6,
      },
      {
        'p1_name': 'Earth',
        'p2_name': 'Sun',
        'aspect': 'conjunction',
        'orbit': 4.9,
      },
      {
        'p1_name': 'Mean_North_Lunar_Node',
        'p2_name': 'True_South_Lunar_Node',
        'aspect': 'opposition',
        'orbit': 0.5,
      },
      {
        'p1_name': 'Moon',
        'p2_name': 'Pluto',
        'aspect': 'quintile',
        'orbit': 7.8,
      },
    ],
  },
};

const Map<String, dynamic> astroChartComparisonDenseSampleProfile = {
  'chart_data': {
    'subject': {
      'name': 'EliteSync Dense Modern',
      'city': '上海市浦东新区',
      'iso_formatted_local_datetime': '1992-11-02T21:15:00+08:00',
      'sun': {'name': 'Sun', 'abs_pos': 36.20},
      'moon': {'name': 'Moon', 'abs_pos': 88.12},
      'mercury': {'name': 'Mercury', 'abs_pos': 63.44},
      'venus': {'name': 'Venus', 'abs_pos': 59.92},
      'mars': {'name': 'Mars', 'abs_pos': 121.55},
      'jupiter': {'name': 'Jupiter', 'abs_pos': 210.40},
      'saturn': {'name': 'Saturn', 'abs_pos': 250.26},
      'uranus': {'name': 'Uranus', 'abs_pos': 278.45},
      'neptune': {'name': 'Neptune', 'abs_pos': 305.73},
      'pluto': {'name': 'Pluto', 'abs_pos': 247.90},
      'chiron': {'name': 'Chiron', 'abs_pos': 312.28},
      'ascendant': {'name': 'Ascendant', 'abs_pos': 144.45},
      'descendant': {'name': 'Descendant', 'abs_pos': 324.45},
      'medium_coeli': {'name': 'Medium_Coeli', 'abs_pos': 234.45},
      'imum_coeli': {'name': 'Imum_Coeli', 'abs_pos': 54.45},
      'mean_north_lunar_node': {
        'name': 'Mean_North_Lunar_Node',
        'abs_pos': 18.50,
      },
      'true_north_lunar_node': {
        'name': 'True_North_Lunar_Node',
        'abs_pos': 19.10,
      },
      'mean_south_lunar_node': {
        'name': 'Mean_South_Lunar_Node',
        'abs_pos': 198.50,
      },
      'true_south_lunar_node': {
        'name': 'True_South_Lunar_Node',
        'abs_pos': 199.10,
      },
      'earth': {'name': 'Earth', 'abs_pos': 216.10},
      'first_house': {'name': 'First_House', 'abs_pos': 144.45},
      'second_house': {'name': 'Second_House', 'abs_pos': 174.45},
      'third_house': {'name': 'Third_House', 'abs_pos': 204.45},
      'fourth_house': {'name': 'Fourth_House', 'abs_pos': 234.45},
      'fifth_house': {'name': 'Fifth_House', 'abs_pos': 264.45},
      'sixth_house': {'name': 'Sixth_House', 'abs_pos': 294.45},
      'seventh_house': {'name': 'Seventh_House', 'abs_pos': 324.45},
      'eighth_house': {'name': 'Eighth_House', 'abs_pos': 354.45},
      'ninth_house': {'name': 'Ninth_House', 'abs_pos': 24.45},
      'tenth_house': {'name': 'Tenth_House', 'abs_pos': 54.45},
      'eleventh_house': {'name': 'Eleventh_House', 'abs_pos': 84.45},
      'twelfth_house': {'name': 'Twelfth_House', 'abs_pos': 114.45},
    },
    'aspects': [
      {'p1_name': 'Sun', 'p2_name': 'Moon', 'aspect': 'sextile', 'orbit': 1.1},
      {'p1_name': 'Sun', 'p2_name': 'Mercury', 'aspect': 'trine', 'orbit': 1.6},
      {'p1_name': 'Moon', 'p2_name': 'Venus', 'aspect': 'square', 'orbit': 2.0},
      {
        'p1_name': 'Jupiter',
        'p2_name': 'Saturn',
        'aspect': 'opposition',
        'orbit': 3.4,
      },
      {
        'p1_name': 'Mercury',
        'p2_name': 'Mars',
        'aspect': 'semisquare',
        'orbit': 1.5,
      },
      {
        'p1_name': 'Ascendant',
        'p2_name': 'Medium_Coeli',
        'aspect': 'square',
        'orbit': 1.3,
      },
      {
        'p1_name': 'Earth',
        'p2_name': 'Sun',
        'aspect': 'conjunction',
        'orbit': 2.7,
      },
      {
        'p1_name': 'Mean_North_Lunar_Node',
        'p2_name': 'True_South_Lunar_Node',
        'aspect': 'opposition',
        'orbit': 0.6,
      },
      {
        'p1_name': 'Moon',
        'p2_name': 'Pluto',
        'aspect': 'quintile',
        'orbit': 2.2,
      },
      {
        'p1_name': 'Sun',
        'p2_name': 'Jupiter',
        'aspect': 'quintile',
        'orbit': 1.9,
      },
      {
        'p1_name': 'Mercury',
        'p2_name': 'Neptune',
        'aspect': 'quintile',
        'orbit': 1.2,
      },
      {
        'p1_name': 'Venus',
        'p2_name': 'Pluto',
        'aspect': 'quindecile',
        'orbit': 2.4,
      },
    ],
  },
};
